### ISSUE TITLE
[Vue warn]: injection "Symbol(disqus)" not found

### ISSUE THREAD

**Issue by khang-nd** [modbender/vue3-disqus#1]
https://github.com/modbender/vue3-disqus/blob/02e98fac7fc214decb3abcfef18900614f18fc65/src/DisqusComments.vue#L69

Suggest adding a default value to get rid of the warning during development.

```js
     const $disqus = <DisqusInstance>inject(CONSTANTS.DISQUS_CONFIG_KEY, {}); 
```

**Comment by modbender** [comment]
Let me check, I'll try to fix this

**Comment by khang-nd** [comment]
More context: I'm using the DisqusComments component as a standalone, hence the warning.
Here's a repro for your convenience: https://stackblitz.com/edit/vue3-disqus-repros (probably need to open the preview panel in a separate window for Disqus to load, not sure why). If you check the console in the preview, you will see the warning.

**Comment by modbender** [comment]
I've added a default, but I'm not sure if the issue is related to that. If you get this problem again you can post re open this issue.

**Comment by khang-nd** [comment]
It's gone, thanks.
